### ISSUE TITLE
College of cardinals for Druidic religion

### ISSUE THREAD

**Issue by rquinio** [xirsoi/ancientreligions#16] opened 2015-01-15 21:13 UTC
Given that the head of the reformed Druidic religion is called the "circle of druids", I made an attempt some while ago to mod in the cardinal mechanics.

If I remember correctly:
- there was some sort of bug of seats not activating on reformation
- the button to open college of cardinals screen (GFX_religion_open_cardinal_screen) did not seem moddable per religion group (not loading from gfx/pagan_interface)
- a custom pagan screen background was needed, as Christian background looked bad.

In case there is support for this, I could have another look at it.

**Comment by xirsoi** [comment] 2015-01-16 04:15
I know this can be done, I remember reading about it in a VIET thread way way back.
This is actually something I've wanted for reformed Celtic for a long time and fully support it.

I know one of the requirements is a Cardinal-type title, and another is making a duplicate of the cardinal interface for the Celts.

**Comment by xirsoi** [comment] 2015-01-18 06:42
I was thinking also about the number of electors. I think it should be 27, since its 3^3. Three was a holy number to the Celts (many gods were in triads, The Morrigan being a big one, and society was in three castes). Normally you'd use 9, but that seems far to few.

**Comment by rquinio** [comment] 2015-01-22 00:24
Hmm, the problem is that 27 characters cannot fit into the screen...
I did a quick mockup with 13 characters:
![circle_druids_mockup](https://cloud.githubusercontent.com/assets/1886883/5848072/c73361d8-a1d4-11e4-838f-4fac2e985df4.jpg)
Potentially up to 17 characters may fit, if removing the funding / best candidate / next candidate, but hardly more than that.

**Comment by schwarherz** [comment] 2015-01-22 00:27
Actually, believe it or not, 9 would work about perfectly. It might SEEM like too few, but I think it would be balanced rather well. Also going with the "holy number" thing, 3 was a holy number, yes, but 9 was the holiest of numbers because it is three threes.

**Comment by xirsoi** [comment] 2015-01-22 00:42
Oh wow, the Cardinal interface has changed since I last saw it (as you can tell, I haven't played many Catholics..). I remember someone creating a "Better College of Cardinals" mod where they had almost 30 electors, so I thought 27 would be fine.

Nine will have to do, but I still feel it would be too small considering the possibility of Druidic covering all of western Europe (with a player at the helm, its almost inevitable).

Love that its actually in a circle, btw!

**Comment by rquinio** [comment] 2015-01-22 01:27
Was it this mod http://forum.paradoxplaza.com/forum/showthread.php?740416-MOD-Deus-Meus-et-Omnia-College-of-Cardinals-mod ? It's 20 cardinals not 30 ;)

On another topic, I've found workarounds for the 2 issues I had:
1) After reformation, no cardinal gets nominated and cardinal seats remain empty.
Saving and reloading solves it, but that's not good. 
=> Workaround is to kill the head of religion after a few months, so that it kicks-off the nominations properly. I could wrap this into an event where non-reformed heretics capture the Arch druid and sacrifice him to the gods.

2) The "open college of cardinals" icon has a papal hat. 
I didn't manage to override it per religion_group (interface/pagan_interface/*). 
=> Workaround is to replace that icon in .gui with the religious tab icon for all religion groups.

3) The selected druid to become the reformed religious head is "random" (though it's always the first druid in the list of druids of the realm). 
It's usually a holy site owner; but not always... which is kind of messy. This perpetuates via succession, as the new Arch-druid inherits that initial temple holding and looses any holding he has.

**Comment by xirsoi** [comment] 2015-01-22 01:59
1) Have you tried waiting about a month? Or perhaps we could force it by picking 9 druids and giving them the 'cardinal' title? Perhaps we could make the druid that holds the capitol of d_celtic_pagan_reformed gain the title?

The sacrifice thing should work, its immersive-ish and the players will understand the necessity. We could always have some events surrounding it to make it more fun.
2) We could probably make this generic enough to fit all the (three) religions that use it if its simply impossible to specify one per religion.
3) That kinda sucks, but it may be possible to jigger something with the sacrifice decision to force a more logical selection.

**Comment by rquinio** [comment] 2015-01-25 23:33
I've done a solution for 1) and 3) combined:
- On reformation, it looks for all holy site holders in the realm and a random one will usurp the title, with preference to one having same culture as reformer (or culture group) - because papal suitability bonus will favor that culture. 
- Usurpation also kicks off the cardinal nominations
- Only case not supported is if player controls 4 holy sites and game selects the 5th as head: will need to save/reload or wait for head's death, but that's an improbable case !

For 2) I've reused the religious tab icon , which works quite well. Can always be changed later if someone designs a better icon.
![religion_icon](https://cloud.githubusercontent.com/assets/1886883/5893799/4f9337f4-a4f2-11e4-8212-1749e74007cd.jpg)

I've kept the UI unchanged for now (except the suitability icon); as my talents for creating a proper background are limited :p 
![circle of druids](https://cloud.githubusercontent.com/assets/1886883/5893803/6422aace-a4f2-11e4-879c-59a453a2721a.jpg)

**Comment by xirsoi** [comment] 2015-01-25 23:35
Beautiful!

**Comment by rquinio** [comment] 2015-01-25 23:49
Thanks !

I've just checked and we're good for holy sites: the 2 temples that are in tribal county (b_whithorn & b_mellifont) always exist.

**Comment by jbelig** [comment] 2015-01-26 00:57
Well, luckily the religious tab icon is quite celtic looking already, but if you wish it shouldn't be hard to make a new one.

**Comment by rquinio** [comment] 2015-01-26 01:08
@jbelig The issue was with religion_open_cardinal_screen.dds 
![religion_open_cardinal_screen](https://cloud.githubusercontent.com/assets/1886883/5894189/83b964ce-a4ff-11e4-8fe9-0bf84331ccc8.jpg)
It applies to all religions with papal succession by default, but only fits Catholics. And I didn't find a way to have vanilla load things from gfx\interface\pagan_interface folder from the mod.

**Comment by jbelig** [comment] 2015-01-26 01:16
I was experimenting with zoroastrian interface and had the same problem when I tried to make it load items from gfx\interface\zoroastrian_interface that were not already in there. If an item was already in the folder and I modifed it, it loaded just fine.
I've asked Arko a bit earlier so we'll see if he can provide some help.

**Comment by xirsoi** [comment] 2015-01-27 03:19
Pull Request Approved and Merged

**Closed by xirsoi** 2015-01-27 03:19 UTC
Labels: enhancement

**Comment by rquinio** [comment] 2015-02-21 16:06
Note: had a look at memory used, but I've seen no noticable impact of ACR  on my PC:
- vanilla (no DLC): 1.12 G
- vanilla with DLCs: 1.17G
- vanilla with DLCs + ACR 1.17G
