### ISSUE TITLE
Falsely confess faith does nothing

### ISSUE THREAD

**Issue by Lietuvis** [xirsoi/ancientreligions#148] opened 2017-06-09 15:11 UTC
Hello,this is me again,i didnt play the mod again until now,the new patch fixed the earlier bug(somehow) but now for some reason the confess faith doesnt work

**Comment by xirsoi** [comment] 2017-06-11 14:41
Could you be more specific?

**Comment by xirsoi** [comment] 2017-07-28 04:10
Closing as Cannot Reproduce and lacking information to fix.

**Closed by xirsoi** 2017-07-28 04:10 UTC
Labels: bug, question
