### ISSUE TITLE
Can't play as a christian

### ISSUE THREAD

**Issue by Lietuvis** [xirsoi/ancientreligions#145] opened 2017-05-11 17:24 UTC
![019](https://cloud.githubusercontent.com/assets/26690001/25962777/5d8df1a2-367f-11e7-957a-0e3d4b9f0bea.jpg)
![018](https://cloud.githubusercontent.com/assets/26690001/25962778/5db11b3c-367f-11e7-960c-216cd8abc541.jpg)
I got another bug,,i can't play any christian character and if i try to play as a any other religion(ex.muslim) it crashes(also i am an idiot because i only remembered the screenshot on steam when i was writing it XD,so sorry for poor quality,i took it with my phone)

**Comment by xirsoi** [comment] 2017-05-11 17:28
Thanks for the report! I can you include your checksum?

**Comment by Lietuvis** [comment] 2017-05-11 17:29
Of course!

**Comment by Lietuvis** [comment] 2017-05-11 19:35
It is UUKG

**Comment by xirsoi** [comment] 2017-05-29 13:03
Closing as Cannot Reproduce

**Closed by xirsoi** 2017-05-29 13:03 UTC
Labels: bug
